#pragma once
#ifndef _KML_GLTF_CONSTANTS_H_
#define _KML_GLTF_CONSTANTS_H_


#define GLTF_MODE_POINTS         (0)
#define GLTF_MODE_LINE           (1)
#define GLTF_MODE_LINE_LOOP      (2)
#define GLTF_MODE_TRIANGLES      (4)
#define GLTF_MODE_TRIANGLE_STRIP (5)
#define GLTF_MODE_TRIANGLE_FAN   (6)

#define GLTF_COMPONENT_TYPE_BYTE           (5120)
#define GLTF_COMPONENT_TYPE_UNSIGNED_BYTE  (5121)
#define GLTF_COMPONENT_TYPE_SHORT          (5122)
#define GLTF_COMPONENT_TYPE_UNSIGNED_SHORT (5123)
#define GLTF_COMPONENT_TYPE_INT            (5124)
#define GLTF_COMPONENT_TYPE_UNSIGNED_INT   (5125)
#define GLTF_COMPONENT_TYPE_FLOAT          (5126)
#define GLTF_COMPONENT_TYPE_DOUBLE         (5130)

#define GLTF_TEXTURE_FILTER_NEAREST                (9728)
#define GLTF_TEXTURE_FILTER_LINEAR                 (9729)
#define GLTF_TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST (9984)
#define GLTF_TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST  (9985)
#define GLTF_TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR  (9986)
#define GLTF_TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR   (9987)

#define GLTF_TEXTURE_WRAP_REPEAT                   (10497)
#define GLTF_TEXTURE_WRAP_CLAMP_TO_EDGE            (33071)
#define GLTF_TEXTURE_WRAP_MIRRORED_REPEAT          (33648)

#define GLTF_TEXTURE_TARGET_TEXTURE2D              (3553)
#define GLTF_TEXTURE_TYPE_UNSIGNED_BYTE            (5121)

#define GLTF_TARGET_ARRAY_BUFFER                   (34962)
#define GLTF_TARGET_ELEMENT_ARRAY_BUFFER           (34963)

#define GLTF_SHADER_TYPE_VERTEX_SHADER             (35633)
#define GLTF_SHADER_TYPE_FRAGMENT_SHADER           (35632)

#endif

